spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/depense
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8088
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

error:
  handling:
    http-statuses:
      jakarta:
        persistence:
          EntityNotFoundException: not_found
          EntityExistsException: conflict
    http-status-in-json-response: true
