spring:
  main:
    web-application-type: reactive
  application:
    name: GatewayService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/money
          jwk-set-uri: http://localhost:8080/realms/money/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: depense
          uri: lb://DEPENSE
          predicates:
            - Path=/depenses/**,/factures/**,/categories/**,/budgets/**
        - id: user
          uri: lb://UTILISATEUR
          predicates:
            - Path=/utilisateurs/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/notifications/**
        - id: projet
          uri: lb://PROJET
          predicates:
            - Path=/projets/**
        - id: revenue
          uri: lb://REVENUE
          predicates:
            - Path=/revenues/**
server:
  port: 3333
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
